Community Routing Filter/Modification
codidact/core pull request #47
Opened 2020-01-30 19:08 UTC by misha130

Closes https://github.com/codidact/core/issues/22

2020-01-30 19:43 UTC, ranolfi commented
All commit messages are clear, except perhaps 7f929c04. Does the term "Modifications" have a special meaning in that context?

2020-01-30 19:45 UTC, misha130 commented
> All commit messages are clear, except perhaps [7f929c0](https://github.com/codidact/core/commit/7f929c04b75c2a1af36ba3662c82dcb63d4ea0d7). Does the term "Modifications" have a special meaning in that context?

Yes. DbContext adds filters on queries and adds the communityId on the entities (modifies them). I couldn't exactly find a different word for it.

2020-01-31 12:03 UTC, ArtOfCode- requested changes

2020-01-31 12:03 UTC, ArtOfCode- commented on src/Domain/Common/Interfaces/ICommunityable.cs
> +    public interface ICommunityable
This reads awkwardly; perhaps use something like `ICommunityScopable`

2020-01-31 12:03 UTC, ArtOfCode- commented on src/WebUI/Services/CurrentCommunityService.cs
> +                //ActionContext needs to exists in order to access community data
Missing space at the start of this comment.

2020-01-31 12:03 UTC, ArtOfCode- commented on src/WebUI/Startup.cs
> +                    );
Closing parenthesis should be on the previous line.

2020-01-31 12:03 UTC, ArtOfCode- commented on tests/Application.UnitTests/Repositories/CommunityRepositoryTest.cs
> +              ).Seed();
Unclear indentation. Try something like this:

```c#
var _sutContext = new ApplicationDbContext(
    new DbContextOptionsBuilder<ApplicationDbContext>()
        .UseInMemoryDatabase(Guid.NewGuid().ToString()).Options,
    new TestCurrentCommunityService()
).Seed();
```

2020-01-31 12:03 UTC, ArtOfCode- commented on tests/Infrastructure.IntegrationTests/Persistence/ApplicationDbContextTests.cs
> +                ).Seed();
Likewise unclear indentation - use a similar pattern to my previous comment.

2020-01-31 12:03 UTC, ArtOfCode- commented on tests/WebUI.IntegrationTests/Services/CurrentCommunityServiceTests.cs
> +        //TODO: Test CurrentCommunityService with a custom IActionContextAccessor
Missing space at the start of this comment.

2020-01-31 13:24 UTC, misha130 commented on src/Domain/Common/Interfaces/ICommunityable.cs
> +    public interface ICommunityable
Agreed, its awkward and scope is a better name.

2020-01-31 17:30 UTC, ArtOfCode- approved these changes

2020-01-31 18:28 UTC, asynts commented on src/Domain/Entities/MemberCommunity.cs
> +        public long ProfileViews { get; set; }
Are these necessary for the MVP?

2020-02-01 15:49 UTC, asynts reviewed
There is a pattern in some of the entity related files:

~~~csharp
/// <summary>
/// Community id of related community
/// </summary>
public long CommunityId { get; set; }

/// <summary>
/// Community instance of related community
/// </summary>
public Community Community { get; set; }
~~~

There might be some performance implications that I am not aware of, but this is redundant since `X.Community.Id = X.CommunityId` for all `X`.

2020-02-01 15:49 UTC, asynts commented on src/Domain/Entities/MemberCommunity.cs
> +        public long ProfileViews { get; set; }
Are these necessary for the MVP?

2020-02-01 15:49 UTC, asynts commented on src/Domain/Entities/MemberCommunity.cs
> +        public bool IsSameAsInstance { get; set; } = true;
If I understand the schema correctly, this just indicates if the bio and the rest are mirrored from the member table. This should be documented.

2020-02-01 15:49 UTC, asynts commented on src/Domain/Entities/MemberCommunity.cs
> +        public Member Member { get; set; }
Refer to summary.

2020-02-01 15:49 UTC, asynts commented on src/Application/Repositories/Communities/CommunityRepository.cs
> +    /// </summary>
Useless comment.

2020-02-01 15:49 UTC, asynts commented on src/Application/Repositories/Communities/CommunityRepository.cs
> +        /// <returns>A task with a community</returns>
Just name the method `GetByNameAsync` and remove the comment?

2020-02-01 15:49 UTC, asynts commented on src/Domain/Common/Interfaces/ICommunityScopable.cs
> +        public Community Community { get; set; }
Refer to summary.

2020-02-01 15:49 UTC, asynts commented on src/Domain/Entities/MemberCommunity.cs
> +        public Community Community { get; set; }
Refer to summary.

2020-02-01 15:49 UTC, asynts commented on src/Domain/Entities/TrustLevelCommunity.cs
> +        /// </summary>
Should be documented.

2020-02-01 15:49 UTC, asynts commented on src/WebUI/Controllers/HomeController.cs
> +using Codidact.Application.Common.Interfaces;
Seems you forgot to undo this.

2020-02-01 15:49 UTC, asynts commented on src/WebUI/Controllers/HomeController.cs
> +            )
Seems you forgot to undo this.

2020-02-01 15:49 UTC, asynts commented on src/WebUI/Services/CurrentCommunityService.cs
> +          )
The parentheses are formatted inconsistently with the other code.

2020-02-01 15:49 UTC, asynts commented on src/Domain/Entities/TrustLevelCommunity.cs
> +        public Community Community { get; set; }
Refer to summary.

2020-02-01 15:55 UTC, misha130 commented on src/Domain/Entities/TrustLevelCommunity.cs
> +        /// </summary>
What does it do? @manassehkatz

2020-02-01 15:56 UTC, misha130 commented
> There is a pattern in some of the entity related files:
> 
> ```cs
> /// <summary>
> /// Community id of related community
> /// </summary>
> public long CommunityId { get; set; }
> 
> /// <summary>
> /// Community instance of related community
> /// </summary>
> public Community Community { get; set; }
> ```
> 
> There might be some performance implications that I am not aware of, but this is redundant since `X.Community.Id = X.CommunityId` for all `X`.

Its for EF to map. It takes the property and understands that the instance must be filled

2020-02-01 15:57 UTC, misha130 commented on src/Domain/Entities/MemberCommunity.cs
> +        public long ProfileViews { get; set; }
Part of https://forum.codidact.org/t/db-schema-round-5/547 so I suppose yes

2020-02-01 16:04 UTC, misha130 commented on src/WebUI/Controllers/HomeController.cs
> +            )
Correct, I rebased because I didn't want this to be in the commits.

2020-02-01 16:08 UTC, misha130 commented on src/Application/Repositories/Communities/CommunityRepository.cs
> +    /// </summary>
Thing is I comment to keep a standard not to really explain.
I'd let @ArtOfCode- & @ranolfi decide what to do. 

I'd rather every method and class have a comment to be honest.

2020-02-01 16:09 UTC, misha130 commented on src/Application/Repositories/Communities/CommunityRepository.cs
> +        /// <returns>A task with a community</returns>
Maybe, actually  `GetSingleByNameAsync` might be the most correct name here

2020-02-01 16:10 UTC, misha130 commented on src/WebUI/Services/CurrentCommunityService.cs
> +          )
https://github.com/codidact/core/pull/47/commits/7bd62b462963595cb066bbd287e3cdd7716045d6

2020-02-01 16:23 UTC, asynts commented
> Its for EF to map. It takes the property and understands that the instance must be filled

I know that it works, I just feel like it's unnecessary.

2020-02-01 16:29 UTC, misha130 commented
> > Its for EF to map. It takes the property and understands that the instance must be filled
> 
> I know that it works, I just feel like it's unnecessary.

You mean the community instance is unnecessary and it shouldn't be enforced? It should only be CommunityId? I can do that. I'll wait to see if some other people have comments.

2020-02-01 16:39 UTC, asynts commented
@misha130 No, the other way around, get the id using `X.Community.Id`, that's just one character more and more intuitive in my opinion.

2020-02-01 16:43 UTC, misha130 commented
> @misha130 No, the other way around, get the id using `X.Community.Id`, that's just one character more and more intuitive in my opinion.

Can't do that at all. Need the actual Column of CommunityId in the table for this mapping to happen

2020-02-01 17:17 UTC, asynts commented
> Can't do that at all. Need the actual Column of CommunityId in the table for this mapping to happen.

There might be trade-offs that I am not aware of, but the `CommunityId` property should be created automatically by the framework. It is a so-called [shadow property][1], the first example of that link explains this.

  [1]: https://docs.microsoft.com/en-us/ef/core/modeling/shadow-properties

2020-02-01 18:45 UTC, misha130 commented
> > Can't do that at all. Need the actual Column of CommunityId in the table for this mapping to happen.
> 
> There might be trade-offs that I am not aware of, but the `CommunityId` property should be created automatically by the framework. It is a so-called [shadow property](https://docs.microsoft.com/en-us/ef/core/modeling/shadow-properties), the first example of that link explains this.

Alright. I see this as an improvement. So I did this https://github.com/codidact/core/pull/47/commits/74cf78ae30b830a878866891b078a0be5e5230e1
I am not sure the consequences of the queries that are executed behind the scenes but I assume the community instance is only filled if the property is needed.

In general it would make the Entities much slimmer if this is implemented everywhere.

I'll remove this commit if its not acceptable

2020-03-02 17:43 UTC, asynts commented on src/Domain/Common/Interfaces/ICommunityScopable.cs
> +        public Community Community { get; set; }
74cf78ae30b830a878866891b078a0be5e5230e1

2020-03-02 17:43 UTC, asynts commented on src/Domain/Entities/MemberCommunity.cs
> +        public Community Community { get; set; }
74cf78ae30b830a878866891b078a0be5e5230e1

2020-03-02 17:44 UTC, asynts commented on src/Domain/Entities/TrustLevelCommunity.cs
> +        public Community Community { get; set; }
74cf78ae30b830a878866891b078a0be5e5230e1

2020-03-04 14:14 UTC, misha130 commented
Closing this because it was decided to use single community per instance

2020-03-04 14:14 UTC, closed without merging

2020-03-04 14:16 UTC, luap42 commented
@misha130 Are you sure? Can you link me to the decision? /cc @ranolfi

2020-03-04 14:41 UTC, misha130 commented
> @misha130 Are you sure? Can you link me to the decision? /cc @ranolfi

Marc said he will write a forum post about it describing the decision but that didn't happen yet.
It was mostly discussed in the voice chat with Marc, Helmar and Monica that happened on 02/02/2020 so I can't really provide a link.

I am OK with closing it since there was no later discussion or someone saying we should go the other way. (/cc @ArtOfCode- )

Here are some pictures of the architecture:
https://cdn.discordapp.com/attachments/641360136908046336/673624516965957662/Network-Use-Cases_User-Data.png
https://cdn.discordapp.com/attachments/641360136908046336/673628362866032727/ResultingArchitecture.png

2020-03-04 15:02 UTC, luap42 commented
I remembered this being about databases,only.

2020-03-04 16:28 UTC, misha130 commented
> I remembered this being about databases,only.

It was later decided to include instances overall 
We could wait for others inputs on the issue, I could reopen this, write a forum post myself?
I am not really sure how to proceed to get a consensus