linter
codidact/core pull request #54
Opened 2020-02-02 19:44 UTC by LionelBergen

Added `dotnet-format`
Ran `dotnet-format` (a few minor whitespace changes)
Added the default `.editorconfig`

Relates to: https://github.com/codidact/core/issues/26

Notes:
There is no way to check for violations without automatically fixing them using this tool. 
For example, we may want to run a check and fail before tests are run, or before a deploy. Rather than asking contributors to run it before/after a merge request.

2020-02-02 20:03 UTC, appgurueu commented
I don't know what MS's style guide says, but personally I can't stand statements like this:
```csharp
if (stuff)
{
     // do stuff
}```
And would prefer
```csharp
if (stuff) {
     // do stuff
}```
Could this be configured? Should it be configured?

2020-02-02 23:37 UTC, ArtOfCode- commented
@appgurueu We're using the Microsoft C# style guide, which is the former style - so, no, we shouldn't configure this to do something different.

2020-02-02 23:38 UTC, ArtOfCode- submitted a review, later dismissed

2020-02-03 01:40 UTC, ranolfi requested changes
@LionelBergen welcome, and thanks. :)

If you can please make the following changes:

1. Separate commits
  - In the first, add the `.editorconfig` file - edit commit message because it says the file is empty which it isn't. Please also specify where you obtained it from. This is important information to be logged in the git history
  - add the `dotnet format` definition to the toolset
  - *then* run it on the codebase.

The first two commits can be combined into one, your call. The last one must be separated.

If you're stuck at some point, just ask ;)

2020-02-03 02:19 UTC, LionelBergen commented
@ranolfi I found it easier to re-make the

2020-02-03 02:19 UTC, closed without merging