Codidact skeleton
codidact/core pull request #7
Opened 2020-01-11 16:22 UTC by misha130

I saw https://github.com/codidact/core/pull/6 and wanted to give this a try of my own.

This includes a folder structure, a basic MVC project that is offered by VS, a tests folder with all test projects. 

There is no ASP.Identity library, there is no EF included since it wasn't fully decided yet.

The folder structure is as follows:

- WebUI - the presentation project
- Application - All business logic of the application
- Domain - All POCOs, enums and such.
- Infrastructure - Persistance (DB), non business logic services, file management etc.

2020-01-11 17:42 UTC, ArtOfCode- commented
Forgive me, but... why do we need two skeletons?

2020-01-11 18:12 UTC, appgurueu commented
> Forgive me, but... why do we need two skeletons?
We only need a single one. But probably @misha130 was not satisfied with the current proposal?

2020-01-11 18:18 UTC, misha130 commented
> We only need a single one. But probably @misha130 was not satisfied with the current proposal?

Yes. I added proper file structure. A setup for unit testing/integration testing. 
I also removed things that are beyond the skeleton such as the authorization framework & EF.
Plus this basically sets the folder architecture.

2020-01-11 19:13 UTC, ArtOfCode- commented
Okay, makes sense. At this point I think it's likely we'll end up using EF Core, but since the decision isn't made yet we can keep it out for now.

2020-01-11 19:15 UTC, ArtOfCode- requested changes
Looks good, other than the fact that Bootstrap is included. We've decided to avoid using Bootstrap and will use our own front-end framework instead; this'll need to be removed before we merge.

2020-01-11 19:44 UTC, luap42 commented
I saw, that you are aware of the repository of our design framework Co-Design (design.codidact.org) already. I am not an expert in C#, but would it be possible to somehow download and include the following file (which is always linking to the latest version of CD) during build:

https://raw.githubusercontent.com/codidact/co-design/master/dist/codidact.css

Even better would be integration with SCSS, which would allow sites to override styles, but this shouldn't be/doesn't have to be/isn't part of a skeleton IMO.

2020-01-11 19:57 UTC, ArtOfCode- submitted a review, later dismissed

2020-01-11 21:15 UTC, misha130 commented
> I saw, that you are aware of the repository of our design framework Co-Design (design.codidact.org) already. I am not an expert in C#, but would it be possible to somehow download and include the following file (which is always linking to the latest version of CD) during build:
> 
> https://raw.githubusercontent.com/codidact/co-design/master/dist/codidact.css
> 
> Even better would be integration with SCSS, which would allow sites to override styles, but this shouldn't be/doesn't have to be/isn't part of a skeleton IMO.

Done
A few points:
Had to download the css/css.map to the project because the link you provided just gave ma text/plain rather text/css so Chrome blocked it.
Had to also download the fonts into the project. 
I also took the co-design docs and made a simple page with a menu.
Its actually ready to be designed from this point IMO.

2020-01-11 22:08 UTC, luap42 commented on src/WebUI/Views/Shared/_Layout.cshtml
> +    <script src="~/lib/jquery/dist/jquery.min.js"></script>
Note, that scripts should be loaded asynchronous or deferred according to the coding standards :
https://github.com/codidact/core/wiki/Code-standards:-HTML#25-links-and-scripts

2020-01-12 13:18 UTC, misha130 commented on src/WebUI/Views/Shared/_Layout.cshtml
> +    <script src="~/lib/jquery/dist/jquery.min.js"></script>
Removed jQuery.
Set site script as async.

2020-01-13 20:03 UTC, ArtOfCode- approved these changes

2020-01-13 20:03 UTC, ArtOfCode- commented
Merging. We need to get developing.

2020-01-13 20:04 UTC, merged